# Copyright (c) 2024 Christopher Watson
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Build Go binaries

on:
  push:
      paths-ignore:
      - 'docs/screenshot.png'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Compile
        uses: xxxserxxx/actions/golang-build@v2.2.3
        env:
            SRCPATH: ./cmd/go-up
        with:
            args: darwin/amd64/1 darwin/arm64/1 linux/amd64 linux/386 linux/arm64 linux/arm7 linux/arm6 linux/arm5 windows/amd64/1 windows/386/1 freebsd/amd64/1
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-up
          path: ./release/go-up_*